"""Bundle frontend/css/*.css into a single frontend/style.bundled.css.

Python port of scripts/bundle_css.sh — used at startup so dev (uvicorn --reload)
gets the same single-file CSS as Docker, eliminating the 22-file @import waterfall.
Regenerates only when the bundle is missing or any source CSS is newer.
"""

from __future__ import annotations

import logging
import re
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

_IMPORT_RE = re.compile(r"@import url\('(css/[^']+\.css)'\)")


def _source_files(frontend: Path) -> list[Path]:
    """Return [style.css, *css/<name>.css] in declared @import order."""
    source = frontend / "style.css"
    text = source.read_text()
    files = [source]
    for rel in _IMPORT_RE.findall(text):
        files.append(frontend / rel)
    return files


def _is_stale(target: Path, sources: list[Path]) -> bool:
    if not target.exists():
        return True
    target_mtime = target.stat().st_mtime
    for src in sources:
        if not src.exists():
            return True
        if src.stat().st_mtime > target_mtime:
            return True
    return False


def regenerate_if_stale(frontend: Path) -> bool:
    """Regenerate frontend/style.bundled.css if any source CSS is newer.

    Returns True if the bundle was (re)written, False if it was already fresh.
    Failure logs a warning and returns False — serve_index falls back to style.css.
    """
    try:
        sources = _source_files(frontend)
    except Exception as exc:
        logger.warning("css_bundle: could not read style.css (%s) — skipping bundle", exc)
        return False

    target = frontend / "style.bundled.css"
    if not _is_stale(target, sources):
        return False

    try:
        chunks = ["/* RoonSage bundled stylesheet — generated by backend/css_bundle.py. */\n"]
        for src in sources[1:]:  # skip style.css itself (it's just @imports)
            rel = src.relative_to(frontend)
            chunks.append(f"\n/* ===== {rel} ===== */\n")
            chunks.append(src.read_text())
        bundled = "".join(chunks)

        # Atomic write so a partial bundle never gets served mid-request.
        fd, tmp_path = tempfile.mkstemp(prefix="style.bundled.", suffix=".css", dir=str(frontend))
        tmp = Path(tmp_path)
        try:
            with open(fd, "w") as f:
                f.write(bundled)
            tmp.replace(target)
        finally:
            if tmp.exists():
                tmp.unlink()
    except Exception as exc:
        logger.warning("css_bundle: regeneration failed (%s)", exc)
        return False

    logger.info("css_bundle: regenerated %s (%d bytes)", target.name, len(bundled))
    return True
