// AUTO-GEGENEREERD uit data/playlist_templates.yaml (63 sjablonen).
// Namen + categorieën in het Nederlands; prompts blijven Engels (LLM-input).
import Foundation

struct PlaylistTemplate: Identifiable, Hashable {
    let id: String
    let name: String
    let icon: String
    let category: String
    let trackCount: Int
    let prompt: String

    /// A monochrome SF Symbol per category, for surfaces that follow the app's
    /// SF-Symbol style (the quick "Snelle sjablonen" chips) rather than the
    /// colour-emoji `icon` used in the full browse sheet.
    var categorySymbol: String {
        switch category {
        case "Sfeer":        "theatermasks"
        case "Activiteiten": "figure.run"
        case "Dagdeel":      "clock"
        case "Tijdperken":   "calendar"
        case "Genres":       "guitars"
        case "Sociaal":      "person.2"
        case "Seizoenen":    "leaf"
        case "Ontdekking":   "sparkles"
        default:             "music.note"
        }
    }
}

enum PlaylistTemplates {
    /// Categorie-volgorde voor de tabs.
    static let categories: [String] = ["Sfeer", "Activiteiten", "Dagdeel", "Tijdperken", "Genres", "Sociaal", "Seizoenen", "Ontdekking"]

    static func inCategory(_ category: String) -> [PlaylistTemplate] {
        all.filter { $0.category == category }
    }

    static let all: [PlaylistTemplate] = [
        PlaylistTemplate(id: "friday-night-chill", name: "Vrijdagavond chill", icon: "🌙", category: "Sfeer", trackCount: 25, prompt: "A melancholic but warm playlist for a Friday evening. Mix of electronic, ambient, and jazz with introspective lyrics. Think late-night city vibes, soft synths, muted horns. Emotional but not heavy. 25 tracks that feel like the end of a long week turning into something peaceful."),
        PlaylistTemplate(id: "sunday-morning", name: "Zondagochtend", icon: "☀️", category: "Sfeer", trackCount: 20, prompt: "A calm, unhurried Sunday morning playlist. Acoustic guitar, gentle vocals, folk and singer-songwriter tracks that feel like sunlight through curtains. Warm, intimate recordings — think coffee, quiet, no rush. 20 tracks with a soft, reflective mood."),
        PlaylistTemplate(id: "rainy-day", name: "Regendag", icon: "🌧️", category: "Sfeer", trackCount: 20, prompt: "A rainy day playlist steeped in atmosphere. Shoegaze, dream pop, and post-rock with lush reverb and introspective mood. Guitars that wash like waves, vocals that blur into the texture. Music that makes rain feel cinematic. 20 deeply immersive tracks to get lost in on a grey afternoon."),
        PlaylistTemplate(id: "melancholic-evening", name: "Melancholische avond", icon: "🥀", category: "Sfeer", trackCount: 25, prompt: "A deeply melancholic but beautiful evening playlist. Slow tempos, minor keys, heartbreak and longing. Sad indie, slowcore, melancholy folk, and downbeat electronica. Songs that don't try to cheer you up — they just sit with you. 25 tracks for when you want to feel something honest."),
        PlaylistTemplate(id: "sunny-optimism", name: "Zonnig optimisme", icon: "🌻", category: "Sfeer", trackCount: 25, prompt: "A bright, sunny optimism playlist. Major keys, jangly guitars, upbeat indie pop, soulful grooves, and feel-good anthems. Music that makes you grin without trying too hard. No saccharine pop — just genuine warmth and energy. 25 tracks to lift the mood instantly."),
        PlaylistTemplate(id: "cozy-autumn", name: "Gezellige herfst", icon: "🍂", category: "Sfeer", trackCount: 25, prompt: "A cozy autumn playlist. Warm acoustic folk, dusky jazz, baroque pop, and indie tracks with rich instrumentation — cello, brushed drums, fingerpicked guitar. Music that smells like coffee and old books. Reflective but never cold. 25 tracks for sweater weather and amber light."),
        PlaylistTemplate(id: "midnight-drive", name: "Middernachtrit", icon: "🌃", category: "Sfeer", trackCount: 30, prompt: "A midnight drive playlist. Synthwave, motorik krautrock, cinematic post-punk, and electronic tracks with a steady forward pulse. Neon-soaked, slightly sinister, deeply hypnotic. Music that makes empty highways feel like a film. 30 tracks built around motion and atmosphere."),
        PlaylistTemplate(id: "golden-hour", name: "Gouden uur", icon: "🌅", category: "Sfeer", trackCount: 25, prompt: "A golden hour playlist for the magic light just before sunset. Soft psychedelic pop, sunlit folk, dreamy soul, and gentle indie. Music that sounds warm and slightly hazy, like memories. Slow-to-mid tempo, warm analog production. 25 tracks that glow."),
        PlaylistTemplate(id: "euphoric-high", name: "Euforie", icon: "✨", category: "Sfeer", trackCount: 25, prompt: "A euphoric playlist full of transcendent moments. Big-room electronic peaks, anthemic indie, gospel-tinged soul, and uplifting post-rock crescendos. Music that feels like sunrise after a long night. 25 tracks built around release, catharsis, and soaring melodies."),
        PlaylistTemplate(id: "introspective", name: "Introspectief", icon: "🪞", category: "Sfeer", trackCount: 20, prompt: "An introspective playlist for deep thinking. Sparse arrangements, whispered vocals, ambient textures, contemplative folk and minimalist classical. Music that creates space rather than filling it. Honest, unhurried, internal. 20 tracks for solitude and reflection."),
        PlaylistTemplate(id: "romantic-mood", name: "Romantische sfeer", icon: "💞", category: "Sfeer", trackCount: 20, prompt: "A romantic mood playlist. Slow soul, intimate jazz, sensual R&B, and tender indie love songs. Sultry without being cliché, tender without being saccharine. Warm, close-mic'd vocals, smoky chord changes. 20 tracks for slow dances and shared quiet."),
        PlaylistTemplate(id: "bittersweet", name: "Bitterzoet", icon: "🍯", category: "Sfeer", trackCount: 25, prompt: "A bittersweet playlist — songs that mix joy and sadness in the same breath. Major-key heartbreakers, hopeful melancholy, indie songs with smiling but teary vocals. Warm but tinged with longing. 25 tracks that resist easy emotional categories."),
        PlaylistTemplate(id: "deep-focus", name: "Diepe focus", icon: "🎯", category: "Activiteiten", trackCount: 30, prompt: "A deep focus playlist for concentration and flow state. Minimal electronic, ambient, and post-rock. Prefer instrumental tracks or tracks with minimal vocals that don't distract. Consistent tempo and texture, no sudden changes. 30 tracks that help the brain lock in for hours of focused work."),
        PlaylistTemplate(id: "workout-energy", name: "Workout-energie", icon: "💪", category: "Activiteiten", trackCount: 35, prompt: "A high-energy workout playlist. Hard-hitting rock, driving electronic, and energetic hip-hop. Fast tempo, aggressive beats, anthemic hooks. No slow intros — every track should make you want to push harder. 35 tracks that maintain peak energy from start to finish."),
        PlaylistTemplate(id: "road-trip", name: "Roadtrip", icon: "🚗", category: "Activiteiten", trackCount: 40, prompt: "The perfect road trip playlist. Classic rock anthems, indie gems, and upbeat tracks that celebrate open roads and freedom. Mix of decades — timeless songs that sound great with the windows down. Fast enough to keep energy up, melodic enough to sing along. 40 tracks for a long drive with no skip button needed."),
        PlaylistTemplate(id: "dinner-party", name: "Etentje", icon: "🍷", category: "Activiteiten", trackCount: 25, prompt: "A sophisticated dinner party playlist. Smooth jazz, soul, bossa nova, and world music with elegant sensibility. Music that enhances conversation without dominating it — warm, unhurried, refined. Mix of classics and modern takes. 25 tracks that make any gathering feel more special."),
        PlaylistTemplate(id: "cooking-session", name: "Koken", icon: "🍳", category: "Activiteiten", trackCount: 30, prompt: "A kitchen playlist for a cooking session. Upbeat soul, funk, Latin grooves, and feel-good Afrobeat. Mid-to-up tempo, rhythmic, fun to chop vegetables to. Not too aggressive — keeps you moving without overwhelming the senses. 30 tracks that turn dinner prep into a vibe."),
        PlaylistTemplate(id: "studying-hard", name: "Hard studeren", icon: "📚", category: "Activiteiten", trackCount: 30, prompt: "A studying playlist that supports concentration without distraction. Instrumental hip-hop, lo-fi beats, modern minimalist classical, and mellow jazz. Steady mid-tempo grooves, no lyrics that pull focus. Long arcs rather than abrupt changes. 30 tracks for serious study time."),
        PlaylistTemplate(id: "yoga-flow", name: "Yoga-flow", icon: "🧘", category: "Activiteiten", trackCount: 20, prompt: "A yoga flow playlist that supports breath and movement. Ambient drones, world instrumentation (sitar, kora, hang drum), meditative electronics, and slow neo-classical. Gentle pulse, no sudden dynamics. Builds and releases organically. 20 tracks for a full practice — opening, flow, savasana."),
        PlaylistTemplate(id: "house-cleaning", name: "Schoonmaken", icon: "🧹", category: "Activiteiten", trackCount: 30, prompt: "A house cleaning playlist that makes chores fly by. Upbeat pop, disco, modern dance, and feel-good rock. Fast tempo, big hooks, infectious energy. Music you can vacuum, sing, and dance to without thinking. 30 tracks to get the place spotless."),
        PlaylistTemplate(id: "reading-time", name: "Leestijd", icon: "📖", category: "Activiteiten", trackCount: 30, prompt: "A reading playlist for getting lost in a book. Modern classical, ambient piano, soft chamber music, and instrumental folk. No lyrics to pull attention from the page. Warm, intimate recordings — like background candlelight. 30 tracks for long reading sessions."),
        PlaylistTemplate(id: "late-coding", name: "Laat coderen", icon: "💻", category: "Activiteiten", trackCount: 35, prompt: "A late-night coding playlist. Hypnotic techno, ambient electronic, post-rock, and IDM with steady forward motion. Mostly instrumental, no sudden vocals or dynamic spikes. Keeps the brain humming without distracting it. 35 tracks for a long coding session after midnight."),
        PlaylistTemplate(id: "date-night", name: "Date-avond", icon: "🕯️", category: "Activiteiten", trackCount: 25, prompt: "A date night playlist for an intimate evening in. Smooth jazz, classic soul, modern R&B, and warm singer-songwriter tracks. Romantic but not cliché — sophisticated rather than cheesy. Mood-setting without dominating. 25 tracks to share over wine and conversation."),
        PlaylistTemplate(id: "morning-coffee", name: "Ochtendkoffie", icon: "☕", category: "Dagdeel", trackCount: 20, prompt: "A morning coffee playlist for the first hour of the day. Soft acoustic folk, warm indie, gentle soul, and laid-back jazz. Music that wakes you slowly — no shock to the system. Bright but not loud, gentle but not sleepy. 20 tracks for sunrise and steam."),
        PlaylistTemplate(id: "lunch-break", name: "Lunchpauze", icon: "🥪", category: "Dagdeel", trackCount: 20, prompt: "A lunch break playlist for a midday reset. Bright indie pop, soulful grooves, easygoing world music, and breezy jazz. Mid-tempo, refreshing, a small dose of joy in the middle of the day. 20 tracks to recharge between meetings."),
        PlaylistTemplate(id: "afternoon-pickup", name: "Middagboost", icon: "⚡", category: "Dagdeel", trackCount: 25, prompt: "An afternoon pickup playlist for beating the post-lunch slump. Upbeat indie rock, funk, neo-soul, and energetic pop. Mid-to-up tempo, driving rhythms, lift without being aggressive. 25 tracks to power through the rest of the day."),
        PlaylistTemplate(id: "sunset-drive", name: "Zonsondergangrit", icon: "🌇", category: "Dagdeel", trackCount: 25, prompt: "A sunset drive playlist for the golden commute home. Cinematic indie, atmospheric pop, dreamy synthwave, and warm classic rock. Music that makes a highway feel like a film. Mid-tempo, melodic, slightly hazy. 25 tracks for the magic hour behind the wheel."),
        PlaylistTemplate(id: "late-night-lounge", name: "Late-avond lounge", icon: "🥃", category: "Dagdeel", trackCount: 25, prompt: "A late night lounge playlist for the small hours. Trip-hop, downtempo, noir jazz, and smoky lounge electronica. Slow, sultry, slightly mysterious. Music for dim rooms and one more drink. 25 tracks to stretch the night out a little further."),
        PlaylistTemplate(id: "3am-thoughts", name: "Gedachten om 3 uur", icon: "🌌", category: "Dagdeel", trackCount: 20, prompt: "A 3 AM thoughts playlist for when sleep won't come. Sparse ambient, slowcore, whispered folk, lonely piano, and ghostly post-rock. Quiet, vast, slightly unsettling. Music for the loneliest hour of the night. 20 tracks for restless minds."),
        PlaylistTemplate(id: "90s-nostalgia", name: "90's-nostalgie", icon: "📼", category: "Tijdperken", trackCount: 30, prompt: "A 90s nostalgia playlist full of alternative rock, grunge, and britpop from the 1990s. Guitar-driven, angsty but catchy, with that distinct lo-fi warmth of the decade. Mix of big hits and underrated deep cuts. 30 tracks that take you straight back to the era of flannel shirts and mixtapes."),
        PlaylistTemplate(id: "50s-rock-roll", name: "50's rock-'n-roll", icon: "🎸", category: "Tijdperken", trackCount: 25, prompt: "A 1950s rock and roll playlist that captures the birth of rock. Chuck Berry-style guitar shuffles, doo-wop harmonies, early rockabilly, and raw rhythm and blues. Energetic, dance-ready, dripping with reverb and tape hiss. 25 tracks from the decade that invented the form."),
        PlaylistTemplate(id: "60s-psychedelic", name: "60's psychedelica", icon: "🌀", category: "Tijdperken", trackCount: 25, prompt: "A 1960s psychedelic playlist. Trippy guitars, sitars, swirling organs, and mind-bending studio production. British psych, San Francisco acid rock, garage psych obscurities. Lush, kaleidoscopic, slightly chaotic. 25 tracks that capture the decade's experimental peak."),
        PlaylistTemplate(id: "70s-soul-funk", name: "70's soul & funk", icon: "🪩", category: "Tijdperken", trackCount: 30, prompt: "A 1970s soul and funk playlist. Deep grooves, lush string arrangements, Philly soul, Stax classics, P-funk, and the early disco moment. Tight horns, warm bass, falsetto vocals. 30 tracks of pure decade-defining groove from soul's richest era."),
        PlaylistTemplate(id: "80s-synthwave", name: "80's synthwave", icon: "🎹", category: "Tijdperken", trackCount: 30, prompt: "A 1980s synth playlist. Neon-drenched synths, gated reverb drums, anthemic choruses, new wave melancholy, and proto-synthwave epics. Equal parts pop sheen and synthetic drama. 30 tracks from the decade that synthesizers conquered the charts."),
        PlaylistTemplate(id: "2000s-indie", name: "2000's indie", icon: "🎧", category: "Tijdperken", trackCount: 30, prompt: "A 2000s indie playlist. Dance-punk, garage rock revival, the early indie blog era, and the post-punk renaissance. Skinny jeans, angular guitars, sharp drums, hooky choruses. 30 tracks that defined a decade of indie taking over the mainstream."),
        PlaylistTemplate(id: "2010s-pop", name: "2010's pop", icon: "📱", category: "Tijdperken", trackCount: 30, prompt: "A 2010s pop playlist. Big choruses, modern hybrid production, EDM-pop crossovers, alt-pop breakthroughs, and the streaming-era hits. Both mainstream chart toppers and the indie-pop tracks that crossed over. 30 tracks from the decade pop reinvented itself."),
        PlaylistTemplate(id: "late-night-jazz", name: "Late-avond jazz", icon: "🎷", category: "Genres", trackCount: 20, prompt: "A late-night jazz playlist drawing from the golden era of jazz. Cool jazz, hard bop, modal jazz from the 1950s and 1970s. Think Blue Note Records, smoky clubs, late-night conversations. Mix of piano trios, quartets, and solo instruments. 20 tracks with deep groove and sophisticated improvisation."),
        PlaylistTemplate(id: "electronic-trip", name: "Elektronische trip", icon: "🛸", category: "Genres", trackCount: 30, prompt: "An electronic trip playlist that flows as a journey. Start with ambient and downtempo, build through deep techno and house, peak with euphoric melodic electronic, then come down through IDM and beatless drift. 30 tracks designed as a single arc, not a shuffle."),
        PlaylistTemplate(id: "hip-hop-classics", name: "Hiphop-klassiekers", icon: "🎤", category: "Genres", trackCount: 30, prompt: "A hip-hop classics playlist. Boom-bap from the 90s golden era, late-90s / early-00s rap, and a sprinkle of modern essentials. Tight beats, witty bars, jazz-sampled production. Skip the obvious commercial chart hits in favor of head-nodding deep cuts. 30 tracks of essential hip-hop."),
        PlaylistTemplate(id: "blues-foundations", name: "Blues-fundament", icon: "🎻", category: "Genres", trackCount: 25, prompt: "A blues foundations playlist. Mississippi Delta acoustic blues, jump blues, electric Chicago blues, and West Coast blues. Steel guitar, harmonica, growling vocals, slow burn solos. The DNA of rock and soul. 25 tracks tracing the genre's deep roots."),
        PlaylistTemplate(id: "classical-calm", name: "Klassieke rust", icon: "🎼", category: "Genres", trackCount: 20, prompt: "A classical calm playlist. Soft chamber works, piano nocturnes, string adagios, and minimalist neo-classical. Music that breathes slowly and creates space. Quiet dynamics throughout — no thunderous tutti. 20 tracks for tranquil hours."),
        PlaylistTemplate(id: "world-music", name: "Wereldmuziek", icon: "🌍", category: "Genres", trackCount: 30, prompt: "A world music playlist that travels across continents. Afrobeat and desert blues from Africa, Latin grooves and bossa nova from South America, ghazal and qawwali from South Asia, Tuareg guitar from the Sahel. Rhythmic, melodic, deeply human. 30 tracks that map a global pulse."),
        PlaylistTemplate(id: "reggae-vibes", name: "Reggae-vibes", icon: "🌴", category: "Genres", trackCount: 25, prompt: "A reggae vibes playlist. Classic Jamaican roots reggae, rocksteady, lovers rock, and dub. Off-beat skanks, bouncing basslines, conscious lyrics, deep echo. Sun-warmed and unhurried. 25 tracks of authentic reggae across its golden eras."),
        PlaylistTemplate(id: "folk-tradition", name: "Folktraditie", icon: "🪕", category: "Genres", trackCount: 25, prompt: "A folk tradition playlist. American folk revival, British folk-rock, Appalachian ballads, and modern singer-songwriter material rooted in traditional forms. Acoustic guitar, fiddle, banjo, story-driven lyrics. Earthy and timeless. 25 tracks honoring folk's deep lineage."),
        PlaylistTemplate(id: "metal-mayhem", name: "Metal-mayhem", icon: "🤘", category: "Genres", trackCount: 30, prompt: "A metal mayhem playlist across subgenres. Classic heavy metal, thrash, progressive metal, sludge, and modern post-metal. Crushing riffs, technical chops, dynamic builds. Skip generic radio metal — favor bands that push the form. 30 tracks of pure heaviness."),
        PlaylistTemplate(id: "country-roads", name: "Country roads", icon: "🤠", category: "Genres", trackCount: 25, prompt: "A country roads playlist. Outlaw country, classic Bakersfield twang, Americana, and modern alt-country. Pedal steel, storytelling, weathered vocals. Avoid slick modern radio country in favor of grit and authenticity. 25 tracks for highways and heartbreak."),
        PlaylistTemplate(id: "bossa-nova-sunset", name: "Bossa nova-zonsondergang", icon: "🇧🇷", category: "Genres", trackCount: 20, prompt: "A bossa nova sunset playlist. Classic Brazilian bossa, samba-jazz, and modern Brazilian fusion. Whispered vocals, gentle nylon guitar, brushed drums, sophisticated harmony. Warm, breezy, effortlessly cool. 20 tracks for slow sunsets and good company."),
        PlaylistTemplate(id: "punk-spirit", name: "Punk-spirit", icon: "🔥", category: "Genres", trackCount: 30, prompt: "A punk spirit playlist. First-wave punk, post-punk, hardcore, and modern punk descendants. Short songs, raw production, attitude that doesn't apologize. Three chords, two minutes, one big idea per track. 30 tracks of pure punk energy."),
        PlaylistTemplate(id: "house-party", name: "Huisfeest", icon: "🎉", category: "Sociaal", trackCount: 40, prompt: "A house party playlist of dance-floor fillers. Mix of decades — disco, 80s pop hits, 90s dance, modern hip-hop, and indie crossover bangers. Big choruses, beats that don't quit, songs everyone knows the words to. 40 tracks to keep the party going all night."),
        PlaylistTemplate(id: "bbq-vibes", name: "BBQ-vibes", icon: "🔥", category: "Sociaal", trackCount: 30, prompt: "A BBQ vibes playlist. Sunny soul, classic funk, reggae, mellow hip-hop, and easygoing rock. Mid-tempo, infectious grooves, songs that work whether you're at the grill or in the lawn chair. 30 tracks for an afternoon of food, friends, and sunshine."),
        PlaylistTemplate(id: "quiet-conversation", name: "Rustig gesprek", icon: "💬", category: "Sociaal", trackCount: 25, prompt: "A quiet conversation playlist. Subtle jazz, instrumental folk, light bossa, and chamber pop with restrained dynamics. Sets a warm mood without ever stealing focus from the people in the room. 25 tracks for long talks over wine."),
        PlaylistTemplate(id: "family-time", name: "Gezinstijd", icon: "👨‍👩‍👧", category: "Sociaal", trackCount: 30, prompt: "A family time playlist that works across generations. Classic Motown, timeless pop, feel-good indie, gentle folk, and a few well-loved modern hits. Warm, inclusive, never edgy. 30 tracks for living rooms filled with people of all ages."),
        PlaylistTemplate(id: "pre-game", name: "Voorgloeien", icon: "🍻", category: "Sociaal", trackCount: 25, prompt: "A pre-game playlist to get the night started. Hype hip-hop, big-room pop, dance-rock anthems, and party-starter electronic. Tempo and energy build progressively — from confident strut to full hype mode by the end. 25 tracks for getting ready before going out."),
        PlaylistTemplate(id: "winter-warmth", name: "Winterwarmte", icon: "❄️", category: "Seizoenen", trackCount: 25, prompt: "A winter warmth playlist. Crackling acoustic folk, dusky jazz, warm indie with rich strings, and cozy soul. Music that pairs with woolen blankets, fireplaces, and steaming mugs. Inward-looking, glowing, slightly nostalgic. 25 tracks for the coldest nights."),
        PlaylistTemplate(id: "spring-awakening", name: "Lente-ontwaken", icon: "🌱", category: "Seizoenen", trackCount: 25, prompt: "A spring awakening playlist for the first warm days. Bright indie pop, blooming folk, hopeful singer-songwriter material, and jangly guitar pop. Sense of renewal, freshness, sunlight after a long grey winter. 25 tracks that feel like the season turning."),
        PlaylistTemplate(id: "beach-day", name: "Stranddag", icon: "🏖️", category: "Seizoenen", trackCount: 30, prompt: "A beach day playlist. Sun-baked surf rock, tropical pop, breezy reggae, easygoing indie, and modern summer hits. Warm guitar tones, laid-back tempos, salt-air vibe. Music for sand, sea, and zero responsibility. 30 tracks for long sunny afternoons."),
        PlaylistTemplate(id: "crisp-autumn", name: "Frisse herfst", icon: "🍁", category: "Seizoenen", trackCount: 25, prompt: "A crisp autumn playlist. Earthy folk, baroque pop, atmospheric indie, and contemplative singer-songwriter material. Warm acoustic textures, reflective lyrics, the bittersweet beauty of seasonal change. 25 tracks for falling leaves and amber afternoons."),
        PlaylistTemplate(id: "holiday-cheer", name: "Feestdagen", icon: "🎄", category: "Seizoenen", trackCount: 25, prompt: "A holiday cheer playlist that skips the kitsch. Soulful holiday classics, jazz interpretations, indie takes on the season, and warm folk holiday tracks. Festive but tasteful — no novelty songs, no shopping-mall pop. 25 tracks for tree-trimming and quiet snowy nights."),
        PlaylistTemplate(id: "new-discoveries", name: "Nieuwe ontdekkingen", icon: "🔭", category: "Ontdekking", trackCount: 25, prompt: "A playlist that blends your library favorites with fresh discoveries from Qobuz. Mix of familiar tracks and new music you haven't heard yet. Prioritize musical coherence — the new tracks should feel like natural companions to your existing collection. 25 tracks, approximately half from your library and half new discoveries worth exploring."),
        PlaylistTemplate(id: "deep-cuts", name: "Verborgen tracks", icon: "💎", category: "Ontdekking", trackCount: 25, prompt: "A deep cuts playlist that avoids obvious singles. Pull album tracks, B-sides, late-album closers, and the third single nobody played. Music that rewards attention. Curate across the user's library favorites — the buried gems, not the radio hits. 25 tracks that reveal new layers."),
        PlaylistTemplate(id: "underrated-gems", name: "Ondergewaardeerde parels", icon: "🪄", category: "Ontdekking", trackCount: 25, prompt: "An underrated gems playlist. Brilliant tracks from artists who never broke through, criminally overlooked albums, and lost classics from well-known artists. Music that deserves a wider audience. Across genres and decades. 25 tracks of overlooked excellence."),
        PlaylistTemplate(id: "time-machine", name: "Tijdmachine", icon: "⏳", category: "Ontdekking", trackCount: 30, prompt: "A time machine playlist that takes a guided tour across decades. Order tracks chronologically by era, starting in the 60s and moving forward through the 70s, 80s, 90s, 2000s, and 2010s. Each era represented by genuinely defining tracks, not just hits. 30 tracks for a musical journey through time."),
        PlaylistTemplate(id: "genre-bender", name: "Genre-bender", icon: "🔀", category: "Ontdekking", trackCount: 25, prompt: "A genre bender playlist. Tracks that refuse easy categories — jazz-rap fusion, electronic folk, classical-influenced pop, post-rock with hip-hop drums. Music that lives in the cracks between genres. Surprising combinations that work. 25 tracks for open ears."),
    ]
}
