// =============================================================================
// Circadian Auto-Playlist view (Vandaag)
// =============================================================================
//
// Shows today's morning/afternoon/evening playlists generated by the daily
// scheduled task in backend.circadian_auto, with a manual "Genereer nu"
// trigger and a collapsible settings panel.

import { apiCall } from './api.js';

let _initialised = false;

function _esc(s) {
    return String(s ?? '').replace(/[&<>"]/g, c => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;',
    }[c]));
}

function _blockLabel(name) {
    return ({ morning: 'Ochtend', afternoon: 'Middag', evening: 'Avond' }[name]) || name;
}

function _blockIcon(name) {
    return ({ morning: '🌅', afternoon: '☀️', evening: '🌙' }[name]) || '🎵';
}

function _renderBlocks(today) {
    const wrap = document.getElementById('circadian-auto-blocks');
    if (!wrap) return;
    const blocks = ['morning', 'afternoon', 'evening'];
    const lookup = Object.fromEntries((today.playlists || []).map(p => [p.time_block, p]));

    wrap.innerHTML = blocks.map(name => {
        const p = lookup[name];
        if (!p) {
            return `
              <div class="rs-bento-tile" style="padding:18px;display:flex;flex-direction:column;gap:8px;">
                <div style="font-size:1.4rem">${_blockIcon(name)} ${_blockLabel(name)}</div>
                <div style="color:var(--text-muted);font-size:13px;">Nog niet gegenereerd voor vandaag.</div>
              </div>
            `;
        }
        const icon = _blockIcon(name);
        const art = p.art_item_key ? `
            <div style="position:relative;width:100%;">
              <img src="/api/art/${p.art_item_key}?width=220&height=220" alt=""
                   style="width:100%;border-radius:8px;aspect-ratio:1;object-fit:cover;"
                   onerror="this.style.display='none';this.nextElementSibling.style.display='flex';">
              <div style="display:none;width:100%;aspect-ratio:1;border-radius:8px;background:linear-gradient(135deg,var(--color-accent-soft,#3a2a14),#222);align-items:center;justify-content:center;font-size:2.6rem;">${icon}</div>
            </div>` :
            `<div style="width:100%;aspect-ratio:1;border-radius:8px;background:linear-gradient(135deg,var(--color-accent-soft,#3a2a14),#222);display:flex;align-items:center;justify-content:center;font-size:2.6rem;">${icon}</div>`;
        const playBtn = p.result_id
            ? `<button class="btn btn-secondary btn-sm" data-result="${_esc(p.result_id)}">Open</button>`
            : '';
        return `
          <div class="rs-bento-tile" style="padding:18px;display:flex;flex-direction:column;gap:10px;">
            <div style="display:flex;align-items:baseline;justify-content:space-between;">
              <span style="font-size:1.2rem;font-weight:600;">${_blockIcon(name)} ${_blockLabel(name)}</span>
              <span style="color:var(--text-muted);font-size:12px;">${p.track_count || 0} tracks</span>
            </div>
            ${art}
            <div style="font-weight:500;font-size:0.96rem;">${_esc(p.playlist_title || '—')}</div>
            <details>
              <summary style="cursor:pointer;color:var(--text-muted);font-size:12px;">Toon prompt</summary>
              <div style="margin-top:6px;color:var(--text-muted);font-size:12px;line-height:1.4;">${_esc(p.prompt_used || '')}</div>
            </details>
            <div style="display:flex;gap:8px;margin-top:auto;">
              ${playBtn}
              ${p.queued_to_zone ? `<span style="font-size:11px;color:var(--text-muted);">In wachtrij op ${_esc(p.queued_to_zone)}</span>` : ''}
            </div>
          </div>
        `;
    }).join('');

    wrap.querySelectorAll('button[data-result]').forEach(b => {
        b.addEventListener('click', () => {
            location.hash = `result/${b.dataset.result}`;
        });
    });
}

async function _renderSettings(container) {
    container.style.display = '';
    let cfg;
    try {
        cfg = await apiCall('/circadian-auto/settings');
    } catch (e) {
        container.innerHTML = `<div class="cluster-error">Instellingen laden mislukt: ${e.message}</div>`;
        return;
    }

    let zones = [];
    try { zones = await apiCall('/roon/zones'); } catch (_) { zones = []; }

    container.innerHTML = `
      <div class="rs-bento-tile" style="padding:18px;display:flex;flex-direction:column;gap:12px;max-width:560px;">
        <h2 style="margin:0;font-size:1.1rem;">Instellingen</h2>
        <label style="display:flex;align-items:center;gap:8px;font-size:14px;">
          <input type="checkbox" id="ca-enabled" ${cfg.enabled ? 'checked' : ''}> Dagelijks automatisch genereren
        </label>
        <label style="display:flex;flex-direction:column;gap:4px;font-size:13px;">
          <span style="color:var(--text-muted);">Tijdstip (uur, 0–23)</span>
          <input type="number" id="ca-hour" min="0" max="23" value="${cfg.schedule_hour}"
                 class="auto-form-input" style="max-width:80px;">
        </label>
        <label style="display:flex;flex-direction:column;gap:4px;font-size:13px;">
          <span style="color:var(--text-muted);">Aantal tracks per blok</span>
          <input type="number" id="ca-tracks" min="5" max="100" value="${cfg.track_count}"
                 class="auto-form-input" style="max-width:80px;">
        </label>
        <label style="display:flex;flex-direction:column;gap:4px;font-size:13px;">
          <span style="color:var(--text-muted);">Zone voor ochtendplaylist (optioneel)</span>
          <select id="ca-zone" class="auto-form-input">
            <option value="">(geen)</option>
            ${(zones || []).map(z => `<option value="${_esc(z.display_name || z.zone_id)}"
              ${cfg.zone === (z.display_name || z.zone_id) ? 'selected' : ''}>${_esc(z.display_name || z.zone_id)}</option>`).join('')}
          </select>
        </label>
        <label style="display:flex;align-items:center;gap:8px;font-size:14px;">
          <input type="checkbox" id="ca-queue" ${cfg.queue_morning ? 'checked' : ''}> Ochtendplaylist automatisch in wachtrij
        </label>
        <div style="display:flex;gap:8px;">
          <button id="ca-save" class="btn btn-primary btn-sm">Opslaan</button>
          <span id="ca-save-msg" style="font-size:13px;color:var(--text-muted);align-self:center;"></span>
        </div>
      </div>
    `;

    container.querySelector('#ca-save').addEventListener('click', async () => {
        const body = {
            enabled: container.querySelector('#ca-enabled').checked,
            schedule_hour: parseInt(container.querySelector('#ca-hour').value, 10) || 6,
            track_count: parseInt(container.querySelector('#ca-tracks').value, 10) || 25,
            zone: container.querySelector('#ca-zone').value || '',
            queue_morning: container.querySelector('#ca-queue').checked,
        };
        const msg = container.querySelector('#ca-save-msg');
        msg.textContent = 'Opslaan…';
        try {
            await apiCall('/circadian-auto/settings', {
                method: 'POST',
                body: JSON.stringify(body),
            });
            msg.textContent = '✓ Opgeslagen';
            setTimeout(() => { msg.textContent = ''; }, 2500);
        } catch (e) {
            msg.textContent = 'Fout: ' + e.message;
        }
    });
}

async function _refresh() {
    const wrap = document.getElementById('circadian-auto-blocks');
    if (wrap) wrap.innerHTML = '<div style="color:var(--text-muted);">Laden…</div>';
    try {
        const today = await apiCall('/circadian-auto/today');
        _renderBlocks(today);
    } catch (e) {
        if (wrap) wrap.innerHTML = `<div class="cluster-error">Laden mislukt: ${e.message}</div>`;
    }
}

export async function initCircadianAutoView() {
    if (!_initialised) {
        _initialised = true;
        document.getElementById('circadian-auto-generate-btn')?.addEventListener('click', async (e) => {
            const btn = e.currentTarget;
            btn.disabled = true; btn.textContent = 'Genereren…';
            try {
                const res = await apiCall('/circadian-auto/generate', { method: 'POST', body: JSON.stringify({}) });
                if (res.status === 'already_running') {
                    btn.textContent = 'Al bezig…';
                }
            } catch (err) {
                btn.disabled = false; btn.textContent = 'Genereer nu';
                alert('Genereren mislukt: ' + err.message);
                return;
            }

            // Poll /today until all 3 blocks are present or timeout (8 min)
            const deadline = Date.now() + 8 * 60 * 1000;
            const poll = setInterval(async () => {
                try {
                    const today = await apiCall('/circadian-auto/today');
                    _renderBlocks(today);
                    const count = (today.playlists || []).length;
                    btn.textContent = count >= 3 ? 'Genereer nu' : `Genereren… (${count}/3)`;
                    if (count >= 3 || Date.now() > deadline) {
                        clearInterval(poll);
                        btn.disabled = false;
                        btn.textContent = 'Genereer nu';
                    }
                } catch (_) { /* keep polling */ }
            }, 5000);
        });

        document.getElementById('circadian-auto-settings-btn')?.addEventListener('click', () => {
            const panel = document.getElementById('circadian-auto-settings');
            if (!panel) return;
            if (panel.style.display === 'none' || !panel.style.display) {
                _renderSettings(panel);
            } else {
                panel.style.display = 'none';
            }
        });
    }
    await _refresh();
}
