// =============================================================================
// Music Map (v13.0)
// =============================================================================
//
// Interactive 2D scatter plot of every clustered track. Pan with drag, zoom
// with mouse wheel (or pinch on mobile), hover for tooltip, click to play.
//
// Renders to a raw HTML5 Canvas — no external libs. The data points come
// from /api/clustering/data, with one (x_2d, y_2d) per track.

import { apiCall } from './api.js';
import {
    fetchClusterData,
    fetchClusterSummary,
    mountClusteringPanel,
} from './clustering.js';

// 50-color palette generated by stepping the HSL hue ring. Cluster -1
// (HDBSCAN noise) always renders gray.
const PALETTE = Array.from({ length: 50 }, (_, i) => {
    const hue = Math.round((i * 360) / 50);
    return `hsl(${hue} 70% 55%)`;
});
const NOISE_COLOR = '#666';

let _initialized = false;
let _state = null;
let _zoneCache = null;

function colorFor(clusterId) {
    if (clusterId === null || clusterId === undefined || clusterId === -1) return NOISE_COLOR;
    return PALETTE[Math.abs(clusterId) % PALETTE.length];
}

function genreToColor(genre) {
    if (!genre) return NOISE_COLOR;
    let h = 0;
    for (let i = 0; i < genre.length; i++) h = (h * 31 + genre.charCodeAt(i)) >>> 0;
    return PALETTE[h % PALETTE.length];
}

function primaryGenre(track) {
    if (!track.genres) return null;
    try {
        const parsed = JSON.parse(track.genres);
        if (Array.isArray(parsed) && parsed.length) return parsed[0];
    } catch {/* fall through */}
    return String(track.genres).split(',')[0]?.trim() || null;
}

// ---- Coordinate transform ----

function computeBounds(tracks) {
    if (!tracks.length) return { minX: 0, maxX: 1, minY: 0, maxY: 1 };
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    for (const t of tracks) {
        if (t.x_2d < minX) minX = t.x_2d;
        if (t.x_2d > maxX) maxX = t.x_2d;
        if (t.y_2d < minY) minY = t.y_2d;
        if (t.y_2d > maxY) maxY = t.y_2d;
    }
    // Pad 5% so dots don't sit on the canvas edge.
    const padX = (maxX - minX) * 0.05 || 1;
    const padY = (maxY - minY) * 0.05 || 1;
    return { minX: minX - padX, maxX: maxX + padX, minY: minY - padY, maxY: maxY + padY };
}

function makeProjector(canvas, bounds, viewport) {
    // viewport = { offsetX, offsetY, scale } -- scale=1 fits-to-canvas.
    const w = canvas.width;
    const h = canvas.height;
    const bw = bounds.maxX - bounds.minX;
    const bh = bounds.maxY - bounds.minY;
    // unit scale so the bounds map to the canvas; viewport.scale zooms further.
    const baseScale = Math.min(w / bw, h / bh);
    const scale = baseScale * viewport.scale;
    // Center the data, then apply pan offset.
    const cx = w / 2 + viewport.offsetX;
    const cy = h / 2 + viewport.offsetY;
    const bcx = (bounds.minX + bounds.maxX) / 2;
    const bcy = (bounds.minY + bounds.maxY) / 2;
    return (x, y) => ({
        px: cx + (x - bcx) * scale,
        // Invert y — UMAP space has y up; canvas has y down.
        py: cy - (y - bcy) * scale,
    });
}

// ---- Rendering ----

function draw(ctx, s) {
    const canvas = ctx.canvas;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--bg-root').trim() || '#101013';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const project = makeProjector(canvas, s.bounds, s.viewport);
    const searchLower = (s.search || '').toLowerCase().trim();
    const radius = Math.max(1.5, 2.5 * Math.sqrt(s.viewport.scale));

    for (let i = 0; i < s.tracks.length; i++) {
        const t = s.tracks[i];
        const { px, py } = project(t.x_2d, t.y_2d);
        // Skip off-canvas for perf when zoomed in.
        if (px < -20 || px > canvas.width + 20 || py < -20 || py > canvas.height + 20) continue;
        const isMatch = searchLower && (
            (t.title || '').toLowerCase().includes(searchLower) ||
            (t.artist || '').toLowerCase().includes(searchLower)
        );
        const fill = s.colorMode === 'genre' ? genreToColor(primaryGenre(t)) : colorFor(t.cluster_id);
        ctx.beginPath();
        ctx.arc(px, py, isMatch ? radius * 2.4 : radius, 0, Math.PI * 2);
        ctx.fillStyle = fill;
        ctx.globalAlpha = searchLower ? (isMatch ? 1.0 : 0.18) : 0.85;
        ctx.fill();
        if (isMatch) {
            ctx.lineWidth = 1.5;
            ctx.strokeStyle = '#fff';
            ctx.stroke();
        }
    }
    ctx.globalAlpha = 1;
}

function findNearest(s, mx, my, maxDist = 8) {
    const project = makeProjector(s.canvas, s.bounds, s.viewport);
    let best = null;
    let bestD2 = maxDist * maxDist;
    for (const t of s.tracks) {
        const { px, py } = project(t.x_2d, t.y_2d);
        const dx = px - mx;
        const dy = py - my;
        const d2 = dx * dx + dy * dy;
        if (d2 < bestD2) { bestD2 = d2; best = t; }
    }
    return best;
}

// ---- Legend ----

function renderLegend(s) {
    const el = document.getElementById('music-map-legend');
    if (!el) return;
    if (s.colorMode !== 'cluster') {
        el.innerHTML = '<div class="music-map-legend-note">Colored by primary genre.</div>';
        return;
    }
    if (!s.summary || !s.summary.length) {
        el.innerHTML = '';
        return;
    }
    const rows = s.summary.slice(0, 20).map(c => `
        <div class="music-map-legend-row" data-cluster-id="${c.cluster_id}">
            <span class="music-map-legend-swatch" style="background:${colorFor(c.cluster_id)}"></span>
            <span class="music-map-legend-label">
                ${c.is_noise ? 'Outliers' : 'Cluster ' + c.cluster_id}
                ${c.dominant_genre ? ' · <em>' + c.dominant_genre + '</em>' : ''}
            </span>
            <span class="music-map-legend-count">${c.track_count}</span>
        </div>
    `).join('');
    el.innerHTML = rows;
}

// ---- Play ----

async function getDefaultZone() {
    if (_zoneCache) return _zoneCache;
    try {
        const zones = await apiCall('/roon/zones');
        _zoneCache = zones && zones.length ? zones[0].zone_id : null;
    } catch { _zoneCache = null; }
    return _zoneCache;
}

async function playTrack(itemKey) {
    const zoneId = await getDefaultZone();
    if (!zoneId) {
        alert('No Roon zone available to play to.');
        return;
    }
    try {
        await apiCall('/queue', {
            method: 'POST',
            body: JSON.stringify({ item_keys: [itemKey], zone_id: zoneId, mode: 'replace' }),
        });
    } catch (err) {
        alert(`Play failed: ${err.message}`);
    }
}

// ---- View init ----

export async function initMusicMapView() {
    if (_initialized) return;
    _initialized = true;

    const canvas = document.getElementById('music-map-canvas');
    const tooltip = document.getElementById('music-map-tooltip');
    const search = document.getElementById('music-map-search');
    const colorSel = document.getElementById('music-map-color-mode');
    const countEl = document.getElementById('music-map-count');
    const clusterPanel = document.getElementById('music-map-cluster-panel');

    if (!canvas) return;
    const ctx = canvas.getContext('2d');

    _state = {
        canvas,
        tracks: [],
        summary: [],
        bounds: { minX: 0, maxX: 1, minY: 0, maxY: 1 },
        viewport: { offsetX: 0, offsetY: 0, scale: 1 },
        colorMode: 'cluster',
        search: '',
        dragging: false,
        lastX: 0,
        lastY: 0,
    };

    async function loadData() {
        countEl.textContent = 'Loading…';
        try {
            const [data, summary] = await Promise.all([fetchClusterData(), fetchClusterSummary()]);
            _state.tracks = data.tracks || [];
            _state.summary = summary.summaries || [];
            _state.bounds = computeBounds(_state.tracks);
            _state.viewport = { offsetX: 0, offsetY: 0, scale: 1 };
            countEl.textContent = `${_state.tracks.length} tracks · ${summary.n_clusters} clusters`;
            draw(ctx, _state);
            renderLegend(_state);
        } catch (err) {
            countEl.textContent = `Error: ${err.message}`;
        }
    }

    // Clustering panel: shows status + Run button. On completion, refresh data.
    mountClusteringPanel(clusterPanel, { onComplete: loadData });

    // ---- Interactions ----

    canvas.addEventListener('wheel', (e) => {
        e.preventDefault();
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        const factor = e.deltaY < 0 ? 1.15 : 1 / 1.15;
        const oldScale = _state.viewport.scale;
        const newScale = Math.max(0.3, Math.min(40, oldScale * factor));
        // Zoom toward cursor: keep the world point under the cursor stationary.
        const cx = canvas.width / 2 + _state.viewport.offsetX;
        const cy = canvas.height / 2 + _state.viewport.offsetY;
        const dx = mx - cx;
        const dy = my - cy;
        const k = newScale / oldScale;
        _state.viewport.offsetX += dx - dx * k;
        _state.viewport.offsetY += dy - dy * k;
        _state.viewport.scale = newScale;
        draw(ctx, _state);
    }, { passive: false });

    canvas.addEventListener('mousedown', (e) => {
        _state.dragging = true;
        _state.lastX = e.clientX;
        _state.lastY = e.clientY;
    });
    window.addEventListener('mouseup', () => { _state.dragging = false; });
    canvas.addEventListener('mousemove', (e) => {
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        if (_state.dragging) {
            _state.viewport.offsetX += e.clientX - _state.lastX;
            _state.viewport.offsetY += e.clientY - _state.lastY;
            _state.lastX = e.clientX;
            _state.lastY = e.clientY;
            tooltip.hidden = true;
            draw(ctx, _state);
            return;
        }
        const hit = findNearest(_state, mx, my, 10);
        if (hit) {
            tooltip.hidden = false;
            tooltip.style.left = `${mx + 12}px`;
            tooltip.style.top = `${my + 12}px`;
            tooltip.innerHTML = `<strong>${hit.title}</strong><br>${hit.artist}<br><small>${primaryGenre(hit) || ''}</small>`;
        } else {
            tooltip.hidden = true;
        }
    });
    canvas.addEventListener('mouseleave', () => { tooltip.hidden = true; });

    canvas.addEventListener('click', (e) => {
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        const hit = findNearest(_state, mx, my, 10);
        if (hit) playTrack(hit.item_key);
    });

    // Touch (pan only — simple).
    let touchLastX = 0, touchLastY = 0, touchDist = 0;
    canvas.addEventListener('touchstart', (e) => {
        if (e.touches.length === 1) {
            touchLastX = e.touches[0].clientX;
            touchLastY = e.touches[0].clientY;
        } else if (e.touches.length === 2) {
            const dx = e.touches[0].clientX - e.touches[1].clientX;
            const dy = e.touches[0].clientY - e.touches[1].clientY;
            touchDist = Math.hypot(dx, dy);
        }
    }, { passive: true });
    canvas.addEventListener('touchmove', (e) => {
        if (e.touches.length === 1) {
            const x = e.touches[0].clientX;
            const y = e.touches[0].clientY;
            _state.viewport.offsetX += x - touchLastX;
            _state.viewport.offsetY += y - touchLastY;
            touchLastX = x; touchLastY = y;
            draw(ctx, _state);
        } else if (e.touches.length === 2) {
            const dx = e.touches[0].clientX - e.touches[1].clientX;
            const dy = e.touches[0].clientY - e.touches[1].clientY;
            const dist = Math.hypot(dx, dy);
            const factor = dist / (touchDist || dist);
            _state.viewport.scale = Math.max(0.3, Math.min(40, _state.viewport.scale * factor));
            touchDist = dist;
            draw(ctx, _state);
        }
    }, { passive: true });

    search.addEventListener('input', () => {
        _state.search = search.value;
        draw(ctx, _state);
    });

    colorSel.addEventListener('change', () => {
        _state.colorMode = colorSel.value;
        draw(ctx, _state);
        renderLegend(_state);
    });

    await loadData();
}

export function getMusicMapData() { return _state ? { tracks: _state.tracks, bounds: _state.bounds } : null; }
