// =============================================================================
// Music Map (v13.0)
// =============================================================================
//
// Interactive 2D scatter plot of every clustered track. Pan with drag, zoom
// with mouse wheel (or pinch on mobile), hover for tooltip, click to play.
//
// Renders to a raw HTML5 Canvas — no external libs. The data points come
// from /api/clustering/data, with one (x_2d, y_2d) per track.

import { apiCall } from './api.js';
import {
    fetchClusterData,
    fetchClusterLabels,
    fetchClusterSummary,
    mountClusteringPanel,
    runAutoTagClusters,
} from './clustering.js';

// 50-color palette generated by stepping the HSL hue ring. Cluster -1
// (HDBSCAN noise) always renders gray.
const PALETTE = Array.from({ length: 50 }, (_, i) => {
    const hue = Math.round((i * 360) / 50);
    return `hsl(${hue} 70% 55%)`;
});
const NOISE_COLOR = '#5a5a60';

// A small, hand-picked palette keyed by lowercased genre keyword. Anything
// not in the table falls back to a hash-based color so the visual stays
// stable across reloads.
const GENRE_COLORS = {
    'classical': '#a78bfa',
    'jazz': '#fbbf24',
    'electronic': '#22d3ee',
    'rock': '#f87171',
    'pop': '#f472b6',
    'hip hop': '#34d399',
    'hip-hop': '#34d399',
    'rap': '#34d399',
    'r&b': '#fb923c',
    'soul': '#fb923c',
    'funk': '#fdba74',
    'metal': '#9ca3af',
    'punk': '#ef4444',
    'folk': '#84cc16',
    'country': '#eab308',
    'blues': '#60a5fa',
    'reggae': '#10b981',
    'ambient': '#7dd3fc',
    'techno': '#06b6d4',
    'house': '#3b82f6',
    'indie': '#c084fc',
    'soundtrack': '#facc15',
};

let _initialized = false;
let _state = null;
let _zoneCache = null;

function colorFor(clusterId) {
    if (clusterId === null || clusterId === undefined || clusterId === -1) return NOISE_COLOR;
    return PALETTE[Math.abs(clusterId) % PALETTE.length];
}

function genreToColor(genre) {
    if (!genre) return NOISE_COLOR;
    const key = String(genre).toLowerCase().trim();
    for (const [k, v] of Object.entries(GENRE_COLORS)) {
        if (key.includes(k)) return v;
    }
    let h = 0;
    for (let i = 0; i < genre.length; i++) h = (h * 31 + genre.charCodeAt(i)) >>> 0;
    return PALETTE[h % PALETTE.length];
}

function primaryGenre(track) {
    if (!track.genres) return null;
    try {
        const parsed = JSON.parse(track.genres);
        if (Array.isArray(parsed) && parsed.length) return parsed[0];
    } catch { /* fall through */ }
    return String(track.genres).split(',')[0]?.trim() || null;
}

// ---- Coordinate transform ----

function computeBounds(tracks) {
    if (!tracks.length) return { minX: 0, maxX: 1, minY: 0, maxY: 1 };
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    for (const t of tracks) {
        if (t.x_2d < minX) minX = t.x_2d;
        if (t.x_2d > maxX) maxX = t.x_2d;
        if (t.y_2d < minY) minY = t.y_2d;
        if (t.y_2d > maxY) maxY = t.y_2d;
    }
    const padX = (maxX - minX) * 0.05 || 1;
    const padY = (maxY - minY) * 0.05 || 1;
    return { minX: minX - padX, maxX: maxX + padX, minY: minY - padY, maxY: maxY + padY };
}

function makeProjector(canvas, bounds, viewport) {
    const w = canvas.width;
    const h = canvas.height;
    const bw = bounds.maxX - bounds.minX;
    const bh = bounds.maxY - bounds.minY;
    const baseScale = Math.min(w / bw, h / bh);
    const scale = baseScale * viewport.scale;
    const cx = w / 2 + viewport.offsetX;
    const cy = h / 2 + viewport.offsetY;
    const bcx = (bounds.minX + bounds.maxX) / 2;
    const bcy = (bounds.minY + bounds.maxY) / 2;
    return (x, y) => ({
        px: cx + (x - bcx) * scale,
        // Invert y — UMAP space has y up; canvas has y down.
        py: cy - (y - bcy) * scale,
    });
}

// ---- Rendering ----

function draw(ctx, s) {
    const canvas = ctx.canvas;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--bg-root').trim() || '#101013';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const project = makeProjector(canvas, s.bounds, s.viewport);
    const searchLower = (s.search || '').toLowerCase().trim();
    const radius = Math.max(1.5, 2.2 * Math.sqrt(s.viewport.scale));
    const hasSelection = s.selectedClusterId !== null && s.selectedClusterId !== undefined;
    const hasSearch = !!searchLower;

    // Two-pass: dim/outlier dots first, then highlighted dots on top so they
    // visually pop instead of being buried under the noise layer.
    const highlightTracks = [];
    for (let i = 0; i < s.tracks.length; i++) {
        const t = s.tracks[i];
        const { px, py } = project(t.x_2d, t.y_2d);
        if (px < -20 || px > canvas.width + 20 || py < -20 || py > canvas.height + 20) continue;
        const isOutlier = t.cluster_id === -1 || t.cluster_id === null;
        const isSearchMatch = hasSearch && (
            (t.title || '').toLowerCase().includes(searchLower) ||
            (t.artist || '').toLowerCase().includes(searchLower)
        );
        const isClusterMatch = hasSelection && t.cluster_id === s.selectedClusterId;
        const isHighlighted = isSearchMatch || isClusterMatch;

        // Decide alpha + draw the "dim" pass right away; defer highlighted to pass 2.
        if (isHighlighted) {
            highlightTracks.push({ t, px, py });
            continue;
        }

        let alpha;
        if (hasSearch || hasSelection) {
            alpha = isOutlier ? 0.06 : 0.15;
        } else {
            alpha = isOutlier ? 0.35 : 0.85;
        }

        const fill = s.colorMode === 'genre' ? genreToColor(primaryGenre(t)) : colorFor(t.cluster_id);
        ctx.beginPath();
        ctx.arc(px, py, radius, 0, Math.PI * 2);
        ctx.fillStyle = fill;
        ctx.globalAlpha = alpha;
        ctx.fill();
    }

    // Pass 2: highlighted dots on top.
    for (const { t, px, py } of highlightTracks) {
        const fill = s.colorMode === 'genre' ? genreToColor(primaryGenre(t)) : colorFor(t.cluster_id);
        ctx.beginPath();
        ctx.arc(px, py, radius * 2.2, 0, Math.PI * 2);
        ctx.fillStyle = fill;
        ctx.globalAlpha = 1.0;
        ctx.fill();
        ctx.lineWidth = 1.5;
        ctx.strokeStyle = '#fff';
        ctx.globalAlpha = 0.9;
        ctx.stroke();
    }
    ctx.globalAlpha = 1;

    if (s.showLabels) drawClusterLabels(ctx, s, project);
}

function labelForCluster(s, clusterId) {
    // Prefer Last.fm/Roon community labels from /api/clustering/labels; fall
    // back to the dominant_genre on the summary; finally to "Cluster N".
    const rec = s.labels && s.labels[clusterId];
    if (rec && rec.labels && rec.labels.length) return rec.labels[0];
    const sum = (s.summary || []).find(c => c.cluster_id === clusterId);
    if (sum && sum.dominant_genre) return sum.dominant_genre;
    return `Cluster ${clusterId}`;
}

function labelsForCluster(s, clusterId) {
    const rec = s.labels && s.labels[clusterId];
    if (rec && rec.labels && rec.labels.length) return rec.labels;
    const sum = (s.summary || []).find(c => c.cluster_id === clusterId);
    if (sum && sum.dominant_genre) return [sum.dominant_genre];
    return [];
}

function drawClusterLabels(ctx, s, project) {
    // Show one label per top cluster, placed at its (x_2d, y_2d) centroid from
    // the summary endpoint. Skip noise. Skip when zoomed out too far so the
    // labels don't overlap into a wall of text.
    if (!s.summary || !s.summary.length) return;
    const canvas = ctx.canvas;

    // Top-N largest clusters with a centroid. Fewer labels when zoomed out.
    const maxLabels = s.viewport.scale < 1.4 ? 10 : (s.viewport.scale < 3 ? 25 : 60);
    const clusters = s.summary
        .filter(c => !c.is_noise && c.centroid_x !== null && c.centroid_y !== null)
        .slice(0, maxLabels);

    ctx.save();
    ctx.font = '600 11px system-ui, -apple-system, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    const placed = [];
    for (const c of clusters) {
        const { px, py } = project(c.centroid_x, c.centroid_y);
        if (px < 20 || px > canvas.width - 20 || py < 14 || py > canvas.height - 14) continue;
        const label = labelForCluster(s, c.cluster_id);
        // Cheap overlap avoidance: skip labels that collide with one already placed.
        const tw = ctx.measureText(label).width;
        let overlaps = false;
        for (const p of placed) {
            if (Math.abs(p.px - px) < (p.w + tw) / 2 + 6 && Math.abs(p.py - py) < 18) {
                overlaps = true;
                break;
            }
        }
        if (overlaps) continue;
        placed.push({ px, py, w: tw });

        // Pill background for legibility.
        const padX = 6, padY = 3;
        ctx.fillStyle = 'rgba(0, 0, 0, 0.62)';
        ctx.beginPath();
        const rx = px - tw / 2 - padX;
        const ry = py - 8 - padY;
        const rw = tw + padX * 2;
        const rh = 16 + padY * 2 - 2;
        const rr = 8;
        ctx.moveTo(rx + rr, ry);
        ctx.arcTo(rx + rw, ry, rx + rw, ry + rh, rr);
        ctx.arcTo(rx + rw, ry + rh, rx, ry + rh, rr);
        ctx.arcTo(rx, ry + rh, rx, ry, rr);
        ctx.arcTo(rx, ry, rx + rw, ry, rr);
        ctx.closePath();
        ctx.fill();
        ctx.fillStyle = '#fff';
        ctx.fillText(label, px, py);
    }
    ctx.restore();
}

function findNearest(s, mx, my, maxDist = 8) {
    const project = makeProjector(s.canvas, s.bounds, s.viewport);
    let best = null;
    let bestD2 = maxDist * maxDist;
    for (const t of s.tracks) {
        const { px, py } = project(t.x_2d, t.y_2d);
        const dx = px - mx;
        const dy = py - my;
        const d2 = dx * dx + dy * dy;
        if (d2 < bestD2) { bestD2 = d2; best = t; }
    }
    return best;
}

// ---- Cluster focus ----

function focusOnCluster(s, clusterId) {
    // Compute tight bounds for this cluster's points, then update viewport
    // so they fill ~60% of the canvas.
    const points = s.tracks.filter(t => t.cluster_id === clusterId);
    if (!points.length) return;
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    for (const p of points) {
        if (p.x_2d < minX) minX = p.x_2d;
        if (p.x_2d > maxX) maxX = p.x_2d;
        if (p.y_2d < minY) minY = p.y_2d;
        if (p.y_2d > maxY) maxY = p.y_2d;
    }
    const cx = (minX + maxX) / 2;
    const cy = (minY + maxY) / 2;
    const span = Math.max(maxX - minX, maxY - minY, 0.5);
    const fullSpan = Math.max(s.bounds.maxX - s.bounds.minX, s.bounds.maxY - s.bounds.minY);
    // Aim for the cluster to fill ~60% of the canvas.
    const targetScale = Math.min(40, (fullSpan / span) * 0.6);
    s.viewport.scale = Math.max(0.8, targetScale);

    // Now pan so (cx, cy) lands at canvas center.
    const canvas = s.canvas;
    const bw = s.bounds.maxX - s.bounds.minX;
    const bh = s.bounds.maxY - s.bounds.minY;
    const baseScale = Math.min(canvas.width / bw, canvas.height / bh);
    const scale = baseScale * s.viewport.scale;
    const bcx = (s.bounds.minX + s.bounds.maxX) / 2;
    const bcy = (s.bounds.minY + s.bounds.maxY) / 2;
    // We want: canvas.width/2 + offsetX + (cx - bcx) * scale = canvas.width/2
    // -> offsetX = -(cx - bcx) * scale; symmetric for y (inverted).
    s.viewport.offsetX = -(cx - bcx) * scale;
    s.viewport.offsetY = (cy - bcy) * scale;
}

function resetView(s) {
    s.viewport = { offsetX: 0, offsetY: 0, scale: 1 };
    s.selectedClusterId = null;
}

// ---- Legend + selection chip ----

function renderLegend(s) {
    const el = document.getElementById('music-map-legend');
    if (!el) return;
    if (s.colorMode !== 'cluster') {
        const items = Object.entries(GENRE_COLORS).slice(0, 14);
        el.innerHTML = `
          <div class="music-map-legend-hint">Klik op een cluster om erop in te zoomen — of zet hierboven "Kleur op: Cluster".</div>
          ${items.map(([name, color]) => `
            <div class="music-map-legend-row" style="cursor:default">
                <span class="music-map-legend-swatch" style="background:${color}"></span>
                <span class="music-map-legend-label" style="text-transform:capitalize">${name}</span>
            </div>
          `).join('')}
        `;
        return;
    }
    if (!s.summary || !s.summary.length) {
        el.innerHTML = '';
        return;
    }
    const rows = s.summary.slice(0, 20).map(c => `
        <div class="music-map-legend-row ${s.selectedClusterId === c.cluster_id ? 'music-map-legend-row--active' : ''}" data-cluster-id="${c.cluster_id}">
            <span class="music-map-legend-swatch" style="background:${colorFor(c.cluster_id)}"></span>
            <span class="music-map-legend-label">
                ${c.is_noise ? 'Outliers' : 'Cluster ' + c.cluster_id}
                ${c.dominant_genre ? ' · <em>' + c.dominant_genre + '</em>' : ''}
            </span>
            <span class="music-map-legend-count">${c.track_count}</span>
        </div>
    `).join('');
    el.innerHTML = `<div class="music-map-legend-hint">Klik op een cluster om erop in te zoomen.</div>${rows}`;
}

function renderSelectionChip(s) {
    const el = document.getElementById('music-map-selection');
    if (!el) return;
    if (s.selectedClusterId === null || s.selectedClusterId === undefined) {
        el.hidden = true;
        el.innerHTML = '';
        return;
    }
    const c = (s.summary || []).find(x => x.cluster_id === s.selectedClusterId);
    const labels = labelsForCluster(s, s.selectedClusterId);
    const labelTxt = labels.length
        ? labels.slice(0, 3).join(' · ')
        : (c ? `Cluster ${c.cluster_id}` : `Cluster ${s.selectedClusterId}`);
    const countTxt = c ? ` · ${c.track_count} tracks` : '';
    el.hidden = false;
    el.innerHTML = `
      <span><strong>${labelTxt}</strong>${countTxt}</span>
      <button id="music-map-smart-radio" class="btn btn-sm" title="Start Smart Radio vanuit dit cluster">▶ Smart Radio</button>
      <button id="music-map-clear-selection" title="Toon alles">×</button>
    `;
}

// ---- Play ----

async function getDefaultZone() {
    if (_zoneCache) return _zoneCache;
    try {
        const zones = await apiCall('/roon/zones');
        _zoneCache = zones && zones.length ? zones[0].zone_id : null;
    } catch { _zoneCache = null; }
    return _zoneCache;
}

async function playTrack(itemKey) {
    const zoneId = await getDefaultZone();
    if (!zoneId) {
        alert('Geen Roon-zone beschikbaar om naar af te spelen.');
        return;
    }
    try {
        await apiCall('/queue', {
            method: 'POST',
            body: JSON.stringify({ item_keys: [itemKey], zone_id: zoneId, mode: 'replace' }),
        });
    } catch (err) {
        alert(`Afspelen mislukt: ${err.message}`);
    }
}

// ---- View init ----

export async function initMusicMapView() {
    if (_initialized) return;
    _initialized = true;

    const canvas = document.getElementById('music-map-canvas');
    const tooltip = document.getElementById('music-map-tooltip');
    const search = document.getElementById('music-map-search');
    const colorSel = document.getElementById('music-map-color-mode');
    const countEl = document.getElementById('music-map-count');
    const clusterPanel = document.getElementById('music-map-cluster-panel');
    const resetBtn = document.getElementById('music-map-reset');
    const labelsToggle = document.getElementById('music-map-show-labels');
    const legendEl = document.getElementById('music-map-legend');
    const selectionEl = document.getElementById('music-map-selection');

    if (!canvas) return;
    const ctx = canvas.getContext('2d');

    _state = {
        canvas,
        tracks: [],
        summary: [],
        bounds: { minX: 0, maxX: 1, minY: 0, maxY: 1 },
        viewport: { offsetX: 0, offsetY: 0, scale: 1 },
        colorMode: 'genre',
        search: '',
        showLabels: true,
        selectedClusterId: null,
        dragging: false,
        lastX: 0,
        lastY: 0,
    };

    function rerender() {
        draw(ctx, _state);
        renderLegend(_state);
        renderSelectionChip(_state);
    }

    function selectCluster(clusterId) {
        _state.selectedClusterId = clusterId;
        focusOnCluster(_state, clusterId);
        rerender();
    }

    function clearSelection() {
        _state.selectedClusterId = null;
        rerender();
    }

    async function loadData() {
        countEl.textContent = 'Laden…';
        try {
            const [data, summary, labels] = await Promise.all([
                fetchClusterData(),
                fetchClusterSummary(),
                fetchClusterLabels().catch(() => ({ labels: [] })),
            ]);
            _state.tracks = data.tracks || [];
            _state.summary = summary.summaries || [];
            _state.labels = {};
            for (const lbl of (labels.labels || [])) {
                _state.labels[lbl.cluster_id] = lbl;
            }
            _state.bounds = computeBounds(_state.tracks);
            _state.viewport = { offsetX: 0, offsetY: 0, scale: 1 };
            _state.selectedClusterId = null;
            const outliers = _state.summary.find(c => c.is_noise);
            const outlierTxt = outliers ? ` · ${outliers.track_count} outliers` : '';
            countEl.textContent = `${_state.tracks.length} tracks · ${summary.n_clusters} clusters${outlierTxt}`;
            rerender();
        } catch (err) {
            countEl.textContent = `Fout: ${err.message}`;
        }
    }

    // Clustering panel: shows status + Run button. On completion, auto-tag
    // the new clusters then refresh map data + labels.
    mountClusteringPanel(clusterPanel, {
        onComplete: async () => {
            try {
                await runAutoTagClusters();
            } catch (err) {
                console.warn('auto-tag after clustering failed', err);
            }
            await loadData();
        },
    });

    // Delegate clicks for cluster cards in the side panel and rows in the legend.
    clusterPanel.addEventListener('click', (e) => {
        const card = e.target.closest('.cluster-card');
        if (!card) return;
        const cid = parseInt(card.dataset.clusterId, 10);
        if (Number.isNaN(cid) || cid === -1) return;
        selectCluster(cid);
        // Mark active visually (the next refresh from the polling timer may
        // overwrite this, which is fine).
        clusterPanel.querySelectorAll('.cluster-card--active').forEach(el => el.classList.remove('cluster-card--active'));
        card.classList.add('cluster-card--active');
    });

    legendEl.addEventListener('click', (e) => {
        const row = e.target.closest('.music-map-legend-row');
        if (!row || !row.dataset.clusterId) return;
        const cid = parseInt(row.dataset.clusterId, 10);
        if (Number.isNaN(cid) || cid === -1) return;
        if (_state.selectedClusterId === cid) clearSelection();
        else selectCluster(cid);
    });

    selectionEl.addEventListener('click', async (e) => {
        if (e.target.id === 'music-map-clear-selection') {
            clearSelection();
            return;
        }
        if (e.target.id === 'music-map-smart-radio') {
            const cid = _state.selectedClusterId;
            if (cid === null || cid === undefined || cid === -1) return;
            const zoneId = await getDefaultZone();
            if (!zoneId) {
                alert('Geen Roon-zone beschikbaar om naar af te spelen.');
                return;
            }
            // Use the first track in this cluster as the seed so smart_radio
            // doesn't fall back to a random library track.
            const seed = (_state.tracks.find(t => t.cluster_id === cid) || {}).item_key || null;
            const btn = e.target;
            const origText = btn.textContent;
            btn.disabled = true;
            btn.textContent = '⏳ Bouwen…';
            try {
                const { runSmartRadio } = await import('./clustering.js');
                const result = await runSmartRadio({
                    zone_id: zoneId,
                    duration_minutes: 60,
                    seed_item_key: seed,
                    play: true,
                });
                btn.textContent = `▶ ${result.n_tracks || '?'} tracks`;
                setTimeout(() => { btn.textContent = origText; btn.disabled = false; }, 2500);
            } catch (err) {
                btn.disabled = false;
                btn.textContent = origText;
                alert(`Smart Radio mislukt: ${err.message}`);
            }
        }
    });

    // ---- Interactions ----

    canvas.addEventListener('wheel', (e) => {
        e.preventDefault();
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        const factor = e.deltaY < 0 ? 1.15 : 1 / 1.15;
        const oldScale = _state.viewport.scale;
        const newScale = Math.max(0.3, Math.min(40, oldScale * factor));
        const cx = canvas.width / 2 + _state.viewport.offsetX;
        const cy = canvas.height / 2 + _state.viewport.offsetY;
        const dx = mx - cx;
        const dy = my - cy;
        const k = newScale / oldScale;
        _state.viewport.offsetX += dx - dx * k;
        _state.viewport.offsetY += dy - dy * k;
        _state.viewport.scale = newScale;
        draw(ctx, _state);
    }, { passive: false });

    canvas.addEventListener('mousedown', (e) => {
        _state.dragging = true;
        _state.lastX = e.clientX;
        _state.lastY = e.clientY;
        _state.dragMoved = false;
    });
    window.addEventListener('mouseup', () => { _state.dragging = false; });
    canvas.addEventListener('mousemove', (e) => {
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        if (_state.dragging) {
            const ddx = e.clientX - _state.lastX;
            const ddy = e.clientY - _state.lastY;
            if (Math.abs(ddx) + Math.abs(ddy) > 2) _state.dragMoved = true;
            _state.viewport.offsetX += ddx;
            _state.viewport.offsetY += ddy;
            _state.lastX = e.clientX;
            _state.lastY = e.clientY;
            tooltip.hidden = true;
            draw(ctx, _state);
            return;
        }
        const hit = findNearest(_state, mx, my, 10);
        if (hit) {
            tooltip.hidden = false;
            tooltip.style.left = `${mx + 12}px`;
            tooltip.style.top = `${my + 12}px`;
            const meta = [
                hit.bpm ? `${Math.round(hit.bpm)} BPM` : null,
                hit.energy !== null && hit.energy !== undefined ? `E ${hit.energy.toFixed(2)}` : null,
                hit.valence !== null && hit.valence !== undefined ? `V ${hit.valence.toFixed(2)}` : null,
            ].filter(Boolean).join(' · ');
            tooltip.innerHTML = `
                <strong>${hit.title || ''}</strong><br>
                ${hit.artist || ''}
                ${primaryGenre(hit) ? `<br><small>${primaryGenre(hit)}</small>` : ''}
                ${meta ? `<br><small style="opacity:0.75">${meta}</small>` : ''}
                <br><small style="opacity:0.55">Klik om af te spelen</small>
            `;
        } else {
            tooltip.hidden = true;
        }
    });
    canvas.addEventListener('mouseleave', () => { tooltip.hidden = true; });

    canvas.addEventListener('click', (e) => {
        // Suppress click after a drag-pan.
        if (_state.dragMoved) { _state.dragMoved = false; return; }
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        const hit = findNearest(_state, mx, my, 10);
        if (hit) playTrack(hit.item_key);
    });

    // Double-click on a track → focus its cluster.
    canvas.addEventListener('dblclick', (e) => {
        const rect = canvas.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        const hit = findNearest(_state, mx, my, 12);
        if (hit && hit.cluster_id !== null && hit.cluster_id !== -1) {
            selectCluster(hit.cluster_id);
        }
    });

    // Touch (pan + pinch zoom).
    let touchLastX = 0, touchLastY = 0, touchDist = 0;
    canvas.addEventListener('touchstart', (e) => {
        if (e.touches.length === 1) {
            touchLastX = e.touches[0].clientX;
            touchLastY = e.touches[0].clientY;
        } else if (e.touches.length === 2) {
            const dx = e.touches[0].clientX - e.touches[1].clientX;
            const dy = e.touches[0].clientY - e.touches[1].clientY;
            touchDist = Math.hypot(dx, dy);
        }
    }, { passive: true });
    canvas.addEventListener('touchmove', (e) => {
        if (e.touches.length === 1) {
            const x = e.touches[0].clientX;
            const y = e.touches[0].clientY;
            _state.viewport.offsetX += x - touchLastX;
            _state.viewport.offsetY += y - touchLastY;
            touchLastX = x; touchLastY = y;
            draw(ctx, _state);
        } else if (e.touches.length === 2) {
            const dx = e.touches[0].clientX - e.touches[1].clientX;
            const dy = e.touches[0].clientY - e.touches[1].clientY;
            const dist = Math.hypot(dx, dy);
            const factor = dist / (touchDist || dist);
            _state.viewport.scale = Math.max(0.3, Math.min(40, _state.viewport.scale * factor));
            touchDist = dist;
            draw(ctx, _state);
        }
    }, { passive: true });

    search.addEventListener('input', () => {
        _state.search = search.value;
        draw(ctx, _state);
    });

    colorSel.addEventListener('change', () => {
        _state.colorMode = colorSel.value;
        rerender();
    });

    resetBtn.addEventListener('click', () => {
        resetView(_state);
        rerender();
    });

    labelsToggle.addEventListener('change', () => {
        _state.showLabels = labelsToggle.checked;
        draw(ctx, _state);
    });

    await loadData();
}

export function getMusicMapData() { return _state ? { tracks: _state.tracks, bounds: _state.bounds } : null; }
