#!/usr/bin/env bash
# Concatenate frontend/css/*.css in the order declared in frontend/style.css
# into frontend/style.bundled.css. Eliminates the @import waterfall on first
# paint (one request instead of 22).
#
# Run from anywhere — paths are resolved relative to the repo root.
# Re-run after editing any CSS file; the Dockerfile invokes it at build time.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FRONTEND="${REPO_ROOT}/frontend"
CSS_DIR="${FRONTEND}/css"
SOURCE="${FRONTEND}/style.css"
TARGET="${FRONTEND}/style.bundled.css"

if [[ ! -f "${SOURCE}" ]]; then
    echo "bundle_css: ${SOURCE} not found" >&2
    exit 1
fi
if [[ ! -d "${CSS_DIR}" ]]; then
    echo "bundle_css: ${CSS_DIR} not found" >&2
    exit 1
fi

# Atomic write via temp file so a partial bundle never gets served.
TMP="$(mktemp "${TARGET}.XXXXXX")"
trap 'rm -f "${TMP}"' EXIT

{
    echo "/* RoonSage bundled stylesheet — generated by scripts/bundle_css.sh. Do not edit by hand. */"
    # Extract the css/<name>.css paths from @import url('css/...') in style.css,
    # preserving order. Lines without a matching @import are ignored.
    grep -oE "@import url\('css/[^']+\.css'\)" "${SOURCE}" \
        | sed -E "s/^@import url\('(css\/[^']+\.css)'\)$/\1/" \
        | while read -r rel; do
            file="${FRONTEND}/${rel}"
            if [[ ! -f "${file}" ]]; then
                echo "bundle_css: missing ${file}" >&2
                exit 1
            fi
            echo ""
            echo "/* ===== ${rel} ===== */"
            cat "${file}"
        done
} > "${TMP}"

mv "${TMP}" "${TARGET}"
trap - EXIT

bytes=$(wc -c < "${TARGET}" | tr -d ' ')
echo "bundle_css: wrote ${TARGET} (${bytes} bytes)"
